//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeee
    {
        public int EmpId { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string ADDRESS { get; set; }
    }
}
